export const GET_ALL_BREEDS='GET_ALL_BREEDS';
export const GET_BY_NAME='GET_BY_NAME';
export const GET_DETAIL='GET_DETAIL';
export const POST_BREED='POST_BREED';
export const GET_TEMPERAMENTS='GET_TEMPERAMENTS';
export const FILTER_ORIGEN='FILTER_ORIGEN';
export const FILTER_TEMPS='FILTER_TEMPS';
export const ORDER_AZ='ORDER_AZ';
export const ORDER_WEIGHT='ORDER_WEIGHT';

